migrate hook url logic to git::url

diff --git a/git-friends/shell/bash/template/hooks/add-upstream b/git-friends/shell/bash/template/hooks/add-upstream
--- a/git-friends/shell/bash/template/hooks/add-upstream
+++ b/git-friends/shell/bash/template/hooks/add-upstream
@@ -11,19 +11,13 @@ if [[ -z "${upstream_user}" ]]; then
   read -r -p 'Enter upstream user or organization name: ' upstream_user
 fi
 
-if [[ -n "${upstream_user}" ]]; then
-  origin_url="$(git config --get remote.origin.url)"
-  protocol="$(git::url::parse "${origin_url}" 1)"
-  base_url="$(git::url::parse "${origin_url}" 2)"
-  base_separator="$(git::url::parse "${origin_url}" 3)"
-  # user="$(git::url::parse "${origin_url}" 4)"
-  repo="$(git::url::parse "${origin_url}" 5)"
-  upstream_url="${protocol}${base_url}${base_separator}${upstream_user}/${repo}"
-
-  if git::utility::ask "add upstream? ${upstream_url}"; then
-    git remote add upstream "${upstream_url}"
-  fi
-else
-  >&2 echo "ERROR: no upstream name provided; so no upstream added"
+if [[ -z "${upstream_user}" ]]; then
+  >&2 echo 'ERROR: no upstream name provided; so no upstream added'
   exit 1
+fi
+
+if origin_url="$(git config --get remote.origin.url)" \
+  && upstream_url="$(git::url::change_user "${origin_url}" "${upstream_user}")" \
+  && git::utility::ask "add upstream? ${upstream_url}"; then
+    git remote add upstream "${upstream_url}"
 fi
diff --git a/git-friends/shell/bash/template/hooks/http-2-ssh b/git-friends/shell/bash/template/hooks/http-2-ssh
--- a/git-friends/shell/bash/template/hooks/http-2-ssh
+++ b/git-friends/shell/bash/template/hooks/http-2-ssh
@@ -5,19 +5,14 @@ source "${HOME}/.git-friends/src/utility.sh"
 
 exec < /dev/tty
 
-name="${1:-origin}"
+remote="${1:-origin}"
 
-if url="$(git config --get "remote.${name}.url" 2>/dev/null)"; then
-  # protocol="$(git::url::parse "${url}" 1)"
-  base_url="$(git::url::parse "${url}" 2)"
-  user="$(git::url::parse "${url}" 4)"
-  repo="$(git::url::parse "${url}" 5)"
-  ssh_url="git@${base_url}:${user}/${repo}"
-
-  if git::utility::ask "convert remote ${name}: ${url} to ~~~> ${ssh_url}"; then
-    git remote set-url "${name}" "${ssh_url}"
-  fi
-else
-  >&2 echo "ERROR: remote '${name}' not found"
+if ! url="$(git config --get "remote.${remote}.url" 2>/dev/null)"; then
+  >&2 echo "ERROR: remote '${remote}' not found"
   exit 1
+fi
+
+if new_url="$(git::url::change_protocol "${url}" 'ssh')" \
+  && git::utility::ask "convert remote ${remote}: ${url} to ~~~> ${new_url}"; then
+    git remote set-url "${remote}" "${new_url}"
 fi
