remove bash_func dependencies

diff --git a/git-friends/shell/bash/template/hooks/add-upstream b/git-friends/shell/bash/template/hooks/add-upstream
--- a/git-friends/shell/bash/template/hooks/add-upstream
+++ b/git-friends/shell/bash/template/hooks/add-upstream
@@ -1,19 +1,29 @@
 #!/bin/bash
-source $HOME/.bash_func
+# shellcheck source=/dev/null
+source "${HOME}/.git-friends/src/url.sh"
+source "${HOME}/.git-friends/src/utility.sh"
+
 exec < /dev/tty
 
-read -p "${RED}Enter upstream user or organization name: ${RESET}" upstream_user
-if [ -n "$upstream_user" ]; then
-  origin_url=`git config --get remote.origin.url`
-  protocol=`git_url_parse $origin_url 1`
-  base_url=`git_url_parse $origin_url 2`
-  base_separator=`git_url_parse $origin_url 3`
-  user=`git_url_parse $origin_url 4`
-  repo=`git_url_parse $origin_url 5`
+upstream_user="$1"
+
+if [[ -z "${upstream_user}" ]]; then
+  read -r -p 'Enter upstream user or organization name: ' upstream_user
+fi
+
+if [[ -n "${upstream_user}" ]]; then
+  origin_url="$(git config --get remote.origin.url)"
+  protocol="$(git::url::parse "${origin_url}" 1)"
+  base_url="$(git::url::parse "${origin_url}" 2)"
+  base_separator="$(git::url::parse "${origin_url}" 3)"
+  # user="$(git::url::parse "${origin_url}" 4)"
+  repo="$(git::url::parse "${origin_url}" 5)"
   upstream_url="${protocol}${base_url}${base_separator}${upstream_user}/${repo}"
-  if ask "add upstream? $upstream_url"; then
-    git remote add upstream $upstream_url
+
+  if git::utility::ask "add upstream? ${upstream_url}"; then
+    git remote add upstream "${upstream_url}"
   fi
 else
-  echo "${RED}ERROR: no upstream name provided; so no upstream added${RESET}"
+  >&2 echo "ERROR: no upstream name provided; so no upstream added"
+  exit 1
 fi
diff --git a/git-friends/shell/bash/template/hooks/ssh-2-http b/git-friends/shell/bash/template/hooks/ssh-2-http
--- a/git-friends/shell/bash/template/hooks/ssh-2-http
+++ b/git-friends/shell/bash/template/hooks/ssh-2-http
@@ -1,20 +1,23 @@
 #!/bin/bash
-source $HOME/.bash_func
+# shellcheck source=/dev/null
+source "${HOME}/.git-friends/src/url.sh"
+source "${HOME}/.git-friends/src/utility.sh"
+
 exec < /dev/tty
 
-name=`coalesce $1 'origin'`
+name="${1:-origin}"
 
-git config --get remote.${name}.url > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-  url=`git config --get remote.${name}.url`
-  protocol=`git_url_parse ${url} 1`
-  base_url=`git_url_parse ${url} 2`
-  user=`git_url_parse ${url} 4`
-  repo=`git_url_parse ${url} 5`
+if url="$(git config --get "remote.${name}.url" 2>/dev/null)"; then
+  # protocol="$(git::url::parse "${url}" 1)"
+  base_url="$(git::url::parse "${url}" 2)"
+  user="$(git::url::parse "${url}" 4)"
+  repo="$(git::url::parse "${url}" 5)"
   https_url="https://${base_url}/${user}/${repo}"
-  if ask "convert remote $name: $url to ~~~> $https_url"; then
-    git remote set-url $name $https_url
+
+  if git::utility::ask "convert remote ${name}: ${url} to ~~~> ${https_url}"; then
+    git remote set-url "${name}" "${https_url}"
   fi
 else
-  echo "${RED}ERROR: remote ${name} not found"
+  >&2 echo "ERROR: remote '${name}' not found"
+  exit 1
 fi
